SELECT
    DISTINCT A."OBJECT_ID" OPORTUNIDADE,
    TO_CHAR(A."GUID") GUID_OPORTUNIDADE,
    L."YPCON_OBJ_CONT_DESC" DESCRICAO_COMP,
    L."YPCON_PROCTYPE",

    CASE
        WHEN H."OPERACAO_P_DESCRIPTION_20" = 'Rodízio Transpetro' THEN 'O 50565095'
        ELSE B."PROC_ORG"
    END ID_ORG_COMPRAS,

    CASE
        WHEN H."OPERACAO_P_DESCRIPTION_20" = 'Rodízio Transpetro' THEN 'Dispensa - Pequenos Serviços'
        ELSE F."STEXT"
    END ORG_COMPRAS,

    CASE
        WHEN B."PROC_ORG" = 'O 50743400' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50668571' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50592067' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50731210' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50632223' THEN 'ARAUCARIA NITROGENADOS'
        WHEN B."PROC_ORG" = 'O 50625852' THEN 'PB BIOCOMBUSTÍVEL - PBBIO'
        WHEN B."PROC_ORG" = 'O 50701109' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50613916' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50674330' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50579414' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50690247' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50579280' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50690559' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50690560' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50705903' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50759212' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50579410' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50672239' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50615965' THEN 'PETROBRAS LOGÍSTICA DE EXPL E PROD S.A.'
        WHEN B."PROC_ORG" = 'O 50609680' THEN 'Petrobras Netherland'
        WHEN B."PROC_ORG" = 'O 50579413' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50612434' THEN 'Petrobras Netherland'
        WHEN B."PROC_ORG" = 'O 50665861' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50077126' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50059517' THEN 'TESTE'
        WHEN B."PROC_ORG" = 'O 50059208' THEN 'TESTE'
        WHEN B."PROC_ORG" = 'O 50649254' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50696397' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50792546' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50617926' THEN 'Petrobras Netherland'
        WHEN B."PROC_ORG" = 'O 50579282' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50792537' THEN 'PETROBRAS'
        WHEN B."PROC_ORG" = 'O 50579412' THEN 'PETROBRAS'
        WHEN H."OPERACAO_P_DESCRIPTION_20" = 'Rodízio Transpetro' THEN 'TRANSPETRO'
        ELSE J."ORG_COMPRA_YPEMP"
    END EMPRESA,

    A."PROCESS_TYPE",
    H."OPERACAO_P_DESCRIPTION_20" AS Tipo_de_Operacao,
    TO_DATE(utctolocal(to_timestamp(A."CREATED_AT"), 'UTC-3')) Data_Criacao,
    TO_DATE(A."QUOT_DEAD") DATA_FECHAMENTO,
    TO_DATE(UTCTOLOCAL(TO_TIMESTAMP(A."OPEN_TIME"),'UTC-3')) DATA_ABERTURA

FROM (
    SELECT
        "OBJECT_ID",
        "GUID",
        "PROCESS_TYPE",
        "CREATED_AT",
        "QUOT_DEAD",
        "OPEN_TIME"
    FROM "_SYS_BIC"."Petronect.Analytics.SRM.CalculationView/CV_DADOS_OPORTUNIDADE"

    UNION ALL

    SELECT
        "OBJECT_ID",
        "GUID",
        "PROCESS_TYPE",
        "CREATED_AT",
        "QUOT_DEAD",
        "OPEN_TIME"
    FROM "_SYS_BIC"."Petronect.Analytics.SRM.CalculationView/CV_DADOS_LEILAO"
) AS A

LEFT JOIN "_SYS_BIC"."Petronect.Analytics.SRM.CalculationView/CV_ORGANIZACAO_COMPRAS" AS B
    ON A."GUID" = B."GUID_HI"

LEFT JOIN (
    SELECT
        "OBJID",
        "STEXT"
    FROM (
        SELECT
            "OBJID",
            "STEXT",
            ROW_NUMBER() OVER(PARTITION BY "OBJID" ORDER BY "BEGDA" DESC) ORG_RECENTE
        FROM "LT_SCP_JNP"."HRP1000"
        WHERE "LANGU" = 'P' OR "OBJID" = '50077126'
    )
    WHERE "ORG_RECENTE" = 1
) AS F
    ON REPLACE(B."PROC_ORG",'O ','') = F."OBJID"

LEFT JOIN (
    SELECT 
        "OPERACAO_PROCESS_TYPE",
        "OPERACAO_P_DESCRIPTION_20",
        "LANGU" 
    FROM "_SYS_BIC"."Petronect.Analytics.SRM.AttributeView/AT_TIPO_OPERACAO"
    WHERE "LANGU" = 'P'
) AS H
    ON A."PROCESS_TYPE" = H."OPERACAO_PROCESS_TYPE"

LEFT JOIN "_SYS_BIC"."Petronect.Analytics.SRM.AttributeView/AT_HIER_ORG_COMPRA" AS J
    ON A."GUID" = J."ORG_COMPRA_GUID_HI"

LEFT JOIN "LT_SCP_JNP"."BBP_PDHSC" AS L
    ON A."GUID" = L."GUID"

WHERE TO_DATE(A."QUOT_DEAD") >= TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');
