SELECT 
A."GUID",
A."OBJECT_ID",
A."QUOT_DEAD",
B."GUID",
B."OBJECT_ID",
B."DESCRIPTION",
B."PROCESS_TYPE",
B."CREATED_AT",
B."TZONE",
B."OPEN_TIME",
B."QUOT_DEAD",
B."QUOT_DEAD_TIME",
B."START_TIME",
B."BID_ALL_ITMS_IND"
FROM "_SYS_BIC"."Petronect.Analytics.SRM.CalculationView/CV_DADOS_OPORTUNIDADE" AS A
LEFT JOIN "_SYS_BIC"."Petronect.Analytics.SRM.CalculationView/CV_DADOS_LEILAO" AS B
	ON B."OBJECT_ID" = A."OBJECT_ID"
WHERE TO_DATE(A."QUOT_DEAD") >= TO_DATE('2025-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND TO_DATE(A."QUOT_DEAD") <= TO_DATE('2025-06-30 23:59:59', 'YYYY-MM-DD HH24:MI:SS');
